export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const UPDATE_USER = 'UPDATE_USER';
export const GLOBAL_CONTENT_REQUEST = 'GLOBAL_CONTENT_REQUEST';
export const GLOBAL_CONTENT_SUCCESS = 'GLOBAL_CONTENT_SUCCESS';
export const GLOBAL_CONTENT_CLEAR = 'GLOBAL_CONTENT_CLEAR';
export const GLOBAL_IMAGE_UPLOAD = 'GLOBAL_IMAGE_UPLOAD';
export const GLOBAL_IMAGE_SUCCESS = 'GLOBAL_IMAGE_SUCCESS';
export const GLOBAL_SET_IMAGES = 'GLOBAL_SET_IMAGES';

export const GLOBAL_THOUGHT_REQUEST = 'GLOBAL_THOUGHT_REQUEST';
export const GLOBAL_THOUGHT_SUCCESS = 'GLOBAL_THOUGHT_SUCCESS';
export const GLOBAL_THOUGHT_FAILURE = 'GLOBAL_THOUGHT_FAILURE';

export const GLOBAL_SHOW_EDITOR = 'GLOBAL_SHOW_EDITOR';
export const GLOBAL_HIDE_EDITOR = 'GLOBAL_HIDE_EDITOR';